Feature: MainActivity refactoring
Nexters/PomoNyang-Android pull request #143
Opened 2024-10-22 04:54 UTC by HyomK

2024-10-22 05:06 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +                    MainEffect.GoToTimer -> {}
일단 명시적으로 Timer랑 onBoarding navigate하는 Effect는 분리했는데 
사실 appstate & app nav host에서 라우팅 처리를 담당해서 처리한 내용은 없어

2024-10-22 05:06 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +                    MainEffect.GoToTimer -> {}
이후 확장 시 mainactivity에서 처리해야 할 로직이 있을 때 좋을 것 같아서 분리했는데 미사용 코드이니까 없는 편이 나으려나?

2024-10-22 05:06 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +    fun AppScreen(viewState: MainState, mohaNyangAppState: MohaNyangAppState) {
로딩, 에러 화면은 임시로 분리해 놓았고 mvp 2차 디자인 작업할 때 변경할게요

2024-10-22 05:06 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +        GlobalScope.launch { viewModel.updateRecentPomodoroDoneData() }
Viewmodel Scope보다는 Global이 맞는것 같아서 scope 변경은 안했는데 어떠신지

2024-10-22 05:06 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +                withTimeout(FETCH_MAX_TIME) {
네트워크 환경이 느린 경우 대비 3초 max 걸어놓았고, 3초 초과 시 네트워크 다이얼로그 노출

2024-10-22 05:09 UTC, HyomK commented
새로 커밋하니까 pr template이 또 생기는 구나... 이거는 내가 다시 고쳐볼게

2024-10-22 15:12 UTC, lee-ji-hoon requested changes
Activity가 좀 깔끔해지니 보기가 좋아 고생했어~! 리뷰 좀 남겼는데 고민해보구 반영해야겠다 싶은것들만 반영해도 될거 같아

내가 체크한건 아래와 같아

- [ ] 낮은 OS 스플래시 화면 정상 동작
- [ ] 처음 다운로드 + 네트워크 끊은 상태 -> 네트워크 연결 후 온보딩 확인
- [ ] 원래 유저 -> 정상적으로 타이머 화면으로 이동하는지

> 갑자기 Description이 늘어서 뭔가 했더니 push 할때마다 늘어나고 있구나!..

2024-10-22 15:12 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +    fun AppScreen(viewState: MainState, mohaNyangAppState: MohaNyangAppState) {
`NetworkFailDialog` 나 `LoadingScreen` `ErrorScreen` 은 전부 공용으로 특정 화면에서 사용을 하기에도 좋을거 같아서 우선은 모듈로 내려두면 더 좋을거 같네

2024-10-22 15:12 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +    ) {
Composable Modifier 기본 값 추가해줘~!

2024-10-22 15:12 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +}
우리 이제 State나 Event Effect를 ViewModel 위에 두지 말고

xxxEelements 라고 해서 하나의 파일 만들고 거기에 몰아두는건 어떨까?

2024-10-22 15:12 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +    }
개인적으로 이 확장함수가 ViewModel에 꼭 있어야 할 필요는 없다고 생각해서 UserInfoResponse 내부 함수로 만드는건 어떨가?

2024-10-22 15:12 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +                }
`fetchUserInfo` 라는 함수명만 봤을 때는 **유저 정보를 갖고 오는구나** 라고만 느껴졌는데 내부에서 온보딩이나 타이머로 보내는 로직이 포함돼있던데 해당 함수에서 하기 보다는 진짜로 온보딩이나 타이머로 보내야하는 로직 부분에서 `fetchUserInfo` 가 끝난 이후 그 값을 통해서 보내는게 맞지 않을까?

2024-10-23 06:48 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +    fun AppScreen(viewState: MainState, mohaNyangAppState: MohaNyangAppState) {
로딩이랑 에러 작업할때 끌어 쓰려고 했는데 그럼 미리 내려놓겠습니답

2024-10-23 06:49 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +                    MainEffect.GoToTimer -> {}
이거는 달아놓고 pending 으로 뒀었네 난 미사용이여도 지금 처럼 미리미리 작성을 해둬야지 나중에 편하더라고~! 

이렇게 안해두면 else로 처리해야하는 것도 좀 보기 안좋기도 하고?!

2024-10-23 06:51 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +    ) {
모듈로 내리면서 같이 추가하겠습니다~

2024-10-23 06:52 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +}
기존것도 다 옮길건가?-? 다 이전하면 PR 나눠서 한번에 처리할게

2024-10-23 07:05 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +}
기존꺼는 누군가 그 ViewModel을 수정할 일이 생긴다면 그때 하자~!

2024-10-23 07:06 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainActivity.kt
> +    fun AppScreen(viewState: MainState, mohaNyangAppState: MohaNyangAppState) {
나중에 작업할 때 하는거면 한 번에 해도 괜찮아~!

2024-10-23 07:35 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +                }
refresh 하는 부분에 공통으로 쓰여서 한번에 처리하려다 보니 애매해진거 같네 다시 분리해볼게!

2024-10-23 08:24 UTC, HyomK commented
> 새로 커밋하니까 pr template이 또 생기는 구나... 이거는 내가 다시 고쳐볼게

opend 될때만 action 되도록 변경했습니다

2024-10-23 13:08 UTC, lee-ji-hoon approved these changes
레거시했던곳들 걷어내느라 고생했어~! 머지하자

2024-10-23 13:24 UTC, merged