[SCRUM-39] 에러&로딩 화면 구현 및 적용
Nexters/PomoNyang-Android pull request #147
Opened 2024-11-13 08:58 UTC by HyomK

2024-11-13 09:23 UTC, HyomK commented on data/src/main/java/com/pomonyang/mohanyang/data/remote/util/NetworkException.kt
에러 코드는 정리본 받은대로 정리했고, 400 에러는 케이스가 많고 디테일하게 나눌 필요는 없어보여서 400으로 통일했습니다
Exception 이름 고민을 좀 했는데 더 좋은 거 있으면 추천해주세요 ㅎㅎ

2024-11-13 09:23 UTC, HyomK commented on data/src/main/java/com/pomonyang/mohanyang/data/remote/util/NetworkResultCall.kt
> +                    when (response.code()) {
Result failure에서 맵핑해서 던지는 방식으로 구현했어요

2024-11-13 09:23 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
> +open class NetworkViewState(
어떻게 viewmodel에서 관리해야 할 지 짱구를 굴려봤는데 base 코드니까 개선할 점 많이 주세요

2024-11-13 09:23 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
> +    open val isInternalError: Boolean = false,
서버 500에러 발생여부에 따라 스크린 분기를 위한 boolean 값

2024-11-13 09:23 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
> +    open val isInvalidError: Boolean = false,
서버 400에러 발생여부에 따라 스크린 분기를 위한 boolean 값

2024-11-13 09:23 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
> +    open val lastRequestAction: ViewEvent? = null
다시 시도하기 버튼이 있어서  가장 최근에 시도 했던 event action을 hold하는 변수인데
이거를 state로 가지고 있어도 될 지 애매했는데 좋은 방법이 있을까요

2024-11-13 09:29 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/common/LoadingScreen.kt
> +            .pointerInput(Unit) {},
로딩하는 동안 스크린 터치되지 않도록 했습니다

2024-11-22 13:16 UTC, lee-ji-hoon requested changes

2024-11-22 13:16 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
>      }
이 함수가 private이긴해도 나중에 누군가 `온라인 유저 데이터 연결` 같은 동작을 다시 추가하려고 event를 추가한다고 했을 때 `getOrThrow()` 가 있다는 것을 놓치기 쉬울거 같아. 아마 `initializeAppData` 에서 모든 것을 처리하고 싶어서 이렇게 한거 같은데 기존 처럼 onFailure안에서 `InternalException`이나 `Exception` 만 잡는건 별로일까?

2024-11-22 13:16 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +                updateState { copy(isInvalidError = true) }
```kotlin
private val coroutineExceptionHandler = CoroutineExceptionHandler { _, throwable ->
    when (throwable) {
        is TimeoutCancellationException -> {
            updateState { copy(isLoading = false) }
        }

        is InternalException -> {
            updateState { copy(isInternalError = true) }
        }

        is BadRequestException -> {
            updateState { copy(isInvalidError = true) }
        }

        else -> {
            updateState { copy(isInvalidError = true) }
        }
    }
}
```

특정 Exception이 발생했을 때마다 모든 API에서 동일하게 상태를 업데이트 해주는 것은 실수하기가 쉬울거 같아.

예를 들어서 내가 MainViewModel에서 새롭게 A라는 API를 호출하는 함수를 만들었을 때 `InternalException` 이나 `BadRequestException` 에 대한 상태 업데이트를 잊어버린다던지! 그럴 경우를 대비해서 위 같은 `CoroutineExceptionHandler`를 하나 만드는 것도 좋은 방법 같아 보이네

2024-11-22 13:16 UTC, lee-ji-hoon commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
> +    open val lastRequestAction: ViewEvent? = null
이건 State에 딱 맞는거 같아!

2024-11-22 13:16 UTC, lee-ji-hoon commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
> +open class NetworkViewState(
음 지금 구조를 뭔가 변경하기에 시간이 괜찮을까? 라는 생각은 드는데 우선 의견은 남겨둘게~!

지금과 같은 구조에서 만약 연속으로 API Error가 떨어졌는데 그게 500, 400이 내려왔다고 한다면 `isInternalError` `isInvalidError` 이 값들이 다 true로 변경이 될거 같아. 

1. 그럼 그것을 어디선가는 false로 바꿔줘야한다. API가 성공했을 때 모든 Error를 false로 만들어준다? 
2. `isInternalError` `isInvalidError` 둘 다 true면 UI에서는 우선순위를 무엇으로 할 것인가?
   2-1. 유저가 **어떤 Error 인지가 중요할까 아니면 Error라는 상태가 중요할까?** 난 보통의 경우 후자라고 생각해!
   2-2. 어떤 화면은 `isInternalError`을 먼저 분기치고 다른 곳은 `isInvalidError`를 먼저 분기치면 결국에 통일성이 사라지는거 같아.

이런 이유로 나는 구조를 조금 변경했으면 해

```kotlin
sealed interface NetworkState {
    data object InternalError : NetworkState
    data object InvalidError : NetworkState
    data object Success : NetworkState
    data object Loading: NetworkState
}

data class MainState(
    val networkState: NetworkState
)
```

위 형태처럼 관리를 하는건 어떨까 라는 생각은 들고 완벽한 예시는 아니지만 참고할만한 [유튜브](https://youtu.be/NG0PPt-CaYE?si=cYpa9o1YC5lCnkOV&t=550)에서 `ProfielDetails`를 `Local` `Remote`를 나눠놓은 것처럼 `NetworkState`를 관리하는거야!

2024-11-22 13:16 UTC, lee-ji-hoon commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/common/ServerErrorScreen.kt
> +        ) {
```kotlin
Column(
        modifier = modifier.fillMaxSize(),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
   ...
}
```

이런 형태로 축약이 가능할거 같아~!

2024-11-22 13:16 UTC, lee-ji-hoon commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/common/ServerErrorScreen.kt
> +            }
이 Column에는 2개의 Component만 존재해서 꼭 spaceBy로 조절 안해도 될거 같아

```kotlin
        ErrorLottieBox(modifier = Modifier.padding(bottom = MnSpacing.threeXLarge))

        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(MnSpacing.small)
        ) {
            Text(
                style = MnTheme.typography.header4, color = MnTheme.textColorScheme.primary, text = stringResource(id = R.string.server_error_title)
            )
            Text(
                style = MnTheme.typography.subBodyRegular.copy(
                    textAlign = TextAlign.Center
                ),
                color = MnTheme.textColorScheme.secondary,
                text = stringResource(id = R.string.server_error_content)
            )
        }
```

이런 형태로 그리는건 어떨까~!

2024-11-22 13:16 UTC, lee-ji-hoon commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
> +open class NetworkViewState(
근데 이 부분은 시간이 좀 많이 들수도 있을거 같아서 추후 리팩으로 가도 괜찮고 아니면 현재 방법이 더 낫다 싶으면 유지해도 괜찮아!

2024-11-22 13:32 UTC, lee-ji-hoon commented
https://github.com/user-attachments/assets/8726fe34-5783-4abc-bd7f-17ab76fba151

추가로 네트워크 제어가 필요한 부분은 카테고리별 시간 설정 이 부분이 필요할거 같아 보이네 👀

2024-11-24 07:56 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/base/BaseViewElements.kt
> +open class NetworkViewState(
음 연속으로 API Fail이 떨어지는 케이스 고려를 못했네
> 1. 유저가 어떤 Error 인지가 중요할까 아니면 Error라는 상태가 중요할까? 
> 이 부분은 나도 후자라고 생각해. 통일성을 가져가고 싶긴한데 케이스마다 에러 화면이 다르게 나와있어서 어떻게 공통으로 가져가야할 지 어렵네

2024-11-24 08:20 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
>      }
맞아 호출부가 한 곳이고 에러 처리 로직이 반복되는 것 같아서 throw로 던져서 처리한 건데 말해준 것 처럼 다른 곳에서도 사용하게 된다면 분리하는 게 더 좋을 것 같네 반영하겠습니다~~

2024-11-24 08:30 UTC, HyomK commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +                updateState { copy(isInvalidError = true) }
handler 처리도 고려했던 부분인데 
모든 viewmodel에서 networkstate를 사용하는 건 아니니 baseviewmodel에 들어가기엔 부적합해보여서 
networkstate를 사용하는 viewmodel에서 선언해서 사용하는 방식을 말하는 건가?

2024-11-24 11:19 UTC, lee-ji-hoon commented on app/src/main/java/com/pomonyang/mohanyang/MainViewModel.kt
> +                updateState { copy(isInvalidError = true) }
`networkstate를 사용하는 viewmodel에서 선언` 응 딱 이 상황에서만 사용해도 괜찮지 않을까? 라는 생각을 하고 있어!

2024-11-27 08:29 UTC, lee-ji-hoon approved these changes

2024-11-27 08:33 UTC, merged