[SCRUM-54] 잠금화면 타이머 노출 옵션 기능 구현
Nexters/PomoNyang-Android pull request #149
Opened 2024-11-20 08:42 UTC by HyomK

## 작업 내용
- 마이페이지 잠금화면 표시하기 옵션 UI 추가
- 잠금화면 표시 datastore data 추가
- 뽀모도로 서비스 notification setvisiblity 옵션 추가로 잠금화면 옵션 기능 구현

## 체크리스트
- [x] 빌드 확인
- [x] 토글 옵션에 따라 타이머 노출 여부 잘 작동하는 지

## 동작 화면

https://github.com/user-attachments/assets/1ed48c5c-8e57-46bc-92bf-bdeb23425ff7

## 살려주세요

2024-11-20 08:57 UTC, HyomK commented on data/src/main/java/com/pomonyang/mohanyang/data/local/datastore/datasource/notification/NotificationLocalDataSourceImpl.kt
> +        }.first()[LOCKSCREEN_NOTIFICATION_KEY] ?: true
기본 값 true 로 적용했어요

2024-11-20 08:57 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +    private fun getLockScreenVisibility(): Int = runBlocking {
datastore 저장값에 따라 visiblity 설정
public -> content 까지 노출
secure -> 잠금화면 미노출

2024-11-20 08:57 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +        lockScreenVisibility = getLockScreenVisibility()
마이페이지에서 변경한 값이 타이머에 적용되도록 channel create 될 때마다 갱신하도록 구현
PomodorNotificationManager가 재사용되기 때문

2024-11-20 08:57 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +        val notification = buildNotification(contentView, bigContentView, lockScreenVisibility)
저장된 값을 이용하여 update 함

2024-11-20 08:57 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/screen/mypage/MyPageViewModel.kt
> +            val isLockScreenEnabled = appNotificationGranted && pushAlarmRepository.isLockScreenNotificationEnabled()
잠금화면 notification 또한 알림 허용 권한이 있어야 노출 됨

2024-11-22 13:28 UTC, lee-ji-hoon requested changes
NotificationCompat.VISIBILITY_SECRET 란게 있구나 처음 알았네! 고생했어~!

2024-11-22 13:28 UTC, lee-ji-hoon commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +        lockScreenVisibility = getLockScreenVisibility()
내부에서 이 `lockScreenVisibility`을 받을 필요 없이 `buildNotification` 에서만 호출하면 될거 같은데 혹시 다른 의도가 있을까?

```kotlin
    private fun buildNotification(
        contentView: RemoteViews,
        bigContentView: RemoteViews,
    ): Notification = notificationBuilder
        .setCustomContentView(contentView)
        .setCustomBigContentView(bigContentView)
        .setColor(ContextCompat.getColor(context, R.color.notification_background_color))
        .setColorized(true)
        .setVisibility(getLockScreenVisibility())
        .build()
```

2024-11-24 07:42 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +        lockScreenVisibility = getLockScreenVisibility()
```kotlin
    fun updateNotification(category: PomodoroCategoryType?, time: String, overtime: String) {

        val isRest = category == null
        val contentView = createContentView(isRest)
        val bigContentView = createBigContentView(category, time, overtime)
        val notification = buildNotification(contentView, bigContentView, lockScreenVisibility)
```

여기 업데이트 하는 부분에서 계속 buildNotification이 호출 되는데 visiblity 값이 datastore에서 가져오는 값이다보니까

```
    private fun getLockScreenVisibility(): Int = runBlocking {
        if (pushAlarmRepository.isLockScreenNotificationEnabled()) {
            NotificationCompat.VISIBILITY_PUBLIC
        } else {
            NotificationCompat.VISIBILITY_SECRET
        }
    }
```
이렇게 runBlocking으로 걸려서 오는게 비효율적이라 저장하게 했어요

2024-11-24 07:43 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +        lockScreenVisibility = getLockScreenVisibility()
createNotification에서 사용되는 부분은 타이머 시작전에 설정된 값을 갱신하는 용도로 사용됩니다
함수로 따로 빼서 의도를 명확하게 하는 게 좋을 거 같기도 하네요

2024-11-24 11:33 UTC, lee-ji-hoon commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +        lockScreenVisibility = getLockScreenVisibility()
내가 좀 고민됐던게 `lockScreenVisibility` 을 필드값으로 갖고 있을 때 만약 메모리 킬 같은 경우에 내가 설정해놓은 값이 날라갈테니 그때도 괜찮을까? 라는 생각은 있긴한데 특이 케이스니 효민쓰 말대로 함수로 따로 빼서 의도를 명확하게 하는 정도면 좋을거 같네

2024-11-24 16:36 UTC, HyomK commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +        lockScreenVisibility = getLockScreenVisibility()
> 기본 값 설정이 있으니 괜찮지 않을까 싶은데, 단순 궁금으로 메모리 킬 된 후 다시 생성될 때 init 안타나?

2024-11-24 23:13 UTC, lee-ji-hoon commented on presentation/src/main/java/com/pomonyang/mohanyang/presentation/noti/PomodoroNotificationManager.kt
> +        lockScreenVisibility = getLockScreenVisibility()
`PomodoroNotificationManager`가 `ServiceScoped`이다보니 Service가 죽기전까지는 살아있어서 오히려 큰 상관이 없을거 같네 함수화한것 확인했어~!

2024-11-24 23:13 UTC, lee-ji-hoon approved these changes

2024-11-26 06:11 UTC, merged